### ISSUE TITLE
Tried to ape template sample project git@github.com: Permission denied (publickey). fatal: Could not read from remote repository. [APE-1159]

### ISSUE THREAD

**Issue by snarflakes** [ApeWorX/ape-template#11]
### Environment information

- `ape` and plugin versions:

```
$ ape --version
0.6.11

$ ape plugins list

Installed Plugins:
  ens          0.6.1
  vyper        0.6.8
  solidity     0.6.6
  etherscan    0.6.7
  infura       0.6.2
  template     0.6.1
  hardhat      0.6.9
  alchemy      0.6.2
  foundry      0.6.11
  tokens       0.6.1
# ...copy and paste result of above command here...
```

- Python Version: 3.10.6
- OS: win

Problem:

~/contracts$ ape template git@github.com:ApeAcademy/ERC721.git
The authenticity of host 'github.com (192.30.255.112)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: y
Please type 'yes', 'no' or the fingerprint: yes
ERROR: git clone failed with error: Cloning into 'ERC721'...
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Traceback (most recent call last):
  File "/home/snar/.local/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/home/snar/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/snar/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/snar/.local/lib/python3.10/site-packages/ape/_cli.py", line 36, in invoke
    return super().invoke(ctx)
  File "/home/snar/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/snar/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/snar/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/snar/.local/lib/python3.10/site-packages/cookiecutter/cli.py", line 194, in main
    cookiecutter(
  File "/home/snar/.local/lib/python3.10/site-packages/cookiecutter/main.py", line 69, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "/home/snar/.local/lib/python3.10/site-packages/cookiecutter/repository.py", line 106, in determine_repo_dir
    cloned_repo = clone(
  File "/home/snar/.local/lib/python3.10/site-packages/cookiecutter/vcs.py", line 95, in clone
    subprocess.check_output(  # nosec
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'git@github.com:ApeAcademy/ERC721.git']' returned non-zero exit status 128.

**Comment by antazoey** [comment]
no offense, just trying to gauge: have you ever used `git` with `github` before? Do you know that your dev env is setup to use to be able to clone repositories from `git`?

you will get issues like this when your auth is not set up right.

https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository#40009598

**Comment by snarflakes** [comment]
I have used it extensively but on pure linux. I'm working now on windows WSL which appears to be a completely different confusing situation. Thanks for the direction, never had issues with cloning repos from github on my usual linux environ before.  And some mentioning of it in the docs would be great.
